// Define InfoType array
export const InfoType = [
  {
    contentTypeId: '0',
    infoTypeTitle: {
      fldgubun: '일련번호',
      infoname: '제목',
      infotext: '내용',
      serialnum: '반복일련번호',
    },
  },
  {
    contentTypeId: '25',
    infoTypeTitle: {
      subcontentid: '하위콘텐츠ID',
      subdetailalt: '코스이미지설명',
      subdetailimg: '코스이미지',
      subdetailoverview: '코스개요',
      subname: '코스명',
      subnum: '반복일련번호',
    },
  },
  {
    contentTypeId: '32',
    infoTypeTitle: {
      roomcode: '객실코드',
      roomtitle: '객실명칭',
      roomsize1: '객실크기(평)',
      roomcount: '객실수',
      roombasecount: '기준인원',
      roommaxcount: '최대인원',
      roomoffseasonminfee1: '비수기주중최소',
      roomoffseasonminfee2: '비수기주말최소',
      roompeakseasonminfee1: '성수기주중최소',
      roompeakseasonminfee2: '성수기주말최소',
      roomintro: '객실소개',
      roombathfacility: '목욕시설여부',
      roombath: '욕조여부',
      roomhometheater: '홈시어터여부',
      roomaircondition: '에어컨여부',
      roomtv: 'TV 여부',
      roompc: 'PC 여부',
      roomcable: '케이블설치여부',
      roominternet: '인터넷여부',
      roomrefrigerator: '냉장고여부',
      roomtoiletries: '세면도구여부',
      roomsofa: '소파여부',
      roomcook: '취사용품여부',
      roomtable: '테이블여부',
      roomhairdryer: '드라이기여부',
      roomsize2: '객실크기(평방미터)',
      roomimg1: '객실사진1',
      roomimg1alt: '객실사진1 설명',
      cpyrhtDivCd1: '저작권 유형 1',
      roomimg2: '객실사진2',
      roomimg2alt: '객실사진2 설명',
      cpyrhtDivCd2: '저작권 유형 2',
      roomimg3: '객실사진3',
      roomimg3alt: '객실사진3 설명',
      cpyrhtDivCd3: '저작권 유형 3',
      roomimg4: '객실사진4',
      roomimg4alt: '객실사진4 설명',
      cpyrhtDivCd4: '저작권 유형 4',
      roomimg5: '객실사진5',
      roomimg5alt: '객실사진5 설명',
      cpyrhtDivCd5: '저작권 유형 5',
    },
  },
];

// Export InfoType array
export default InfoType;
